-- =============================================================================
-- Phase 1: Snowflake Foundations
-- File: 00_setup.sql
-- Account: demo43  |  AWS Account: 018437500440  |  Region: us-west-2
-- Run as: ACCOUNTADMIN or SYSADMIN with USERADMIN grant
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- ─── Database ─────────────────────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS CRYPTO_SURVEILLANCE
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Digital Asset Market Surveillance & Financial Crime Analytics';

-- ─── Schemas ──────────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS CRYPTO_SURVEILLANCE.RAW
    DATA_RETENTION_TIME_IN_DAYS = 3
    COMMENT = 'Landing zone: raw events from CEX infra and on-chain sources';

CREATE SCHEMA IF NOT EXISTS CRYPTO_SURVEILLANCE.HARMONISED
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Cleansed, typed trade/order/balance/on-chain tables + entity graph';

CREATE SCHEMA IF NOT EXISTS CRYPTO_SURVEILLANCE.FEATURES
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Engineered features for ML scoring (Snowpark Dynamic Tables)';

CREATE SCHEMA IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Alerts, cases, detection rule views, KRI/KPI reporting';

CREATE SCHEMA IF NOT EXISTS CRYPTO_SURVEILLANCE.ML
    DATA_RETENTION_TIME_IN_DAYS = 30
    COMMENT = 'Model registry, training datasets, UDFs, scoring results';

-- ─── Roles ────────────────────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS SURVEILLANCE_ADMIN
    COMMENT = 'Full access to CRYPTO_SURVEILLANCE database';

CREATE ROLE IF NOT EXISTS SURVEILLANCE_ANALYST
    COMMENT = 'Read access to HARMONISED, ANALYTICS; can run investigations';

CREATE ROLE IF NOT EXISTS SURVEILLANCE_INGEST
    COMMENT = 'Write access to RAW schema; used by Snowpipe/streaming connectors';

CREATE ROLE IF NOT EXISTS SURVEILLANCE_ML
    COMMENT = 'Access to FEATURES and ML schemas; used by Snowpark jobs';

-- Role hierarchy
GRANT ROLE SURVEILLANCE_ANALYST TO ROLE SURVEILLANCE_ADMIN;
GRANT ROLE SURVEILLANCE_INGEST  TO ROLE SURVEILLANCE_ADMIN;
GRANT ROLE SURVEILLANCE_ML      TO ROLE SURVEILLANCE_ADMIN;
GRANT ROLE SURVEILLANCE_ADMIN   TO ROLE SYSADMIN;

-- ─── Warehouses (consolidated: 2 instead of 4) ──────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS WH_SURVEILLANCE
    WAREHOUSE_SIZE   = 'MEDIUM'
    AUTO_SUSPEND     = 120
    AUTO_RESUME      = TRUE
    MAX_CLUSTER_COUNT = 3
    MIN_CLUSTER_COUNT = 1
    SCALING_POLICY   = 'STANDARD'
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'General-purpose: ingest, transform, analytics, dashboards, Streamlit';

CREATE WAREHOUSE IF NOT EXISTS WH_ML
    WAREHOUSE_SIZE   = 'LARGE'
    AUTO_SUSPEND     = 300
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Snowpark ML model training and batch scoring runs';

-- ─── Privilege Grants ─────────────────────────────────────────────────────────
GRANT USAGE ON DATABASE CRYPTO_SURVEILLANCE TO ROLE SURVEILLANCE_ADMIN;
GRANT USAGE ON DATABASE CRYPTO_SURVEILLANCE TO ROLE SURVEILLANCE_ANALYST;
GRANT USAGE ON DATABASE CRYPTO_SURVEILLANCE TO ROLE SURVEILLANCE_INGEST;
GRANT USAGE ON DATABASE CRYPTO_SURVEILLANCE TO ROLE SURVEILLANCE_ML;

GRANT ALL PRIVILEGES ON SCHEMA CRYPTO_SURVEILLANCE.RAW         TO ROLE SURVEILLANCE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CRYPTO_SURVEILLANCE.HARMONISED  TO ROLE SURVEILLANCE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CRYPTO_SURVEILLANCE.FEATURES    TO ROLE SURVEILLANCE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CRYPTO_SURVEILLANCE.ANALYTICS   TO ROLE SURVEILLANCE_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA CRYPTO_SURVEILLANCE.ML          TO ROLE SURVEILLANCE_ADMIN;

GRANT USAGE, CREATE TABLE, CREATE PIPE, CREATE STREAM ON SCHEMA CRYPTO_SURVEILLANCE.RAW
    TO ROLE SURVEILLANCE_INGEST;

GRANT USAGE ON SCHEMA CRYPTO_SURVEILLANCE.HARMONISED  TO ROLE SURVEILLANCE_ANALYST;
GRANT USAGE ON SCHEMA CRYPTO_SURVEILLANCE.ANALYTICS   TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CRYPTO_SURVEILLANCE.HARMONISED TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CRYPTO_SURVEILLANCE.ANALYTICS  TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CRYPTO_SURVEILLANCE.HARMONISED TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA CRYPTO_SURVEILLANCE.ANALYTICS  TO ROLE SURVEILLANCE_ANALYST;

GRANT USAGE ON SCHEMA CRYPTO_SURVEILLANCE.FEATURES TO ROLE SURVEILLANCE_ML;
GRANT USAGE ON SCHEMA CRYPTO_SURVEILLANCE.ML        TO ROLE SURVEILLANCE_ML;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CRYPTO_SURVEILLANCE.FEATURES TO ROLE SURVEILLANCE_ML;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CRYPTO_SURVEILLANCE.ML        TO ROLE SURVEILLANCE_ML;

GRANT USAGE ON WAREHOUSE WH_SURVEILLANCE TO ROLE SURVEILLANCE_INGEST;
GRANT USAGE ON WAREHOUSE WH_SURVEILLANCE TO ROLE SURVEILLANCE_ADMIN;
GRANT USAGE ON WAREHOUSE WH_SURVEILLANCE TO ROLE SURVEILLANCE_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ML           TO ROLE SURVEILLANCE_ML;
GRANT USAGE ON WAREHOUSE WH_ML           TO ROLE SURVEILLANCE_ADMIN;

-- ─── Resource Monitor ─────────────────────────────────────────────────────────
CREATE RESOURCE MONITOR IF NOT EXISTS RM_CRYPTO_SURVEILLANCE
    WITH CREDIT_QUOTA = 500
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75  PERCENT DO NOTIFY
        ON 90  PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE WH_SURVEILLANCE SET RESOURCE_MONITOR = RM_CRYPTO_SURVEILLANCE;
ALTER WAREHOUSE WH_ML           SET RESOURCE_MONITOR = RM_CRYPTO_SURVEILLANCE;

-- ─── Marketplace: Snowflake Public Data (Free) ─────────────────────────────
-- Pre-provisioned on most accounts; provides BTC/ETH stock prices & FX rates.
-- Required by VW_MARKETPLACE_PRICES and VW_MARKETPLACE_FX_RATES in 03_harmonised.sql.
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_PUBLIC_DATA_FREE
    TO ROLE SURVEILLANCE_ADMIN;

-- ─── QuickSight Service Account ─────────────────────────────────────────────
-- Used by Amazon QuickSight DIRECT_QUERY data source (PASSWORD auth).
-- Password must match the QuickSight data source credential configuration.
CREATE USER IF NOT EXISTS QUICKSIGHT_SVC
    PASSWORD = 'QsSnow2026!Crypto#Svc'
    DEFAULT_ROLE = SURVEILLANCE_ANALYST
    DEFAULT_WAREHOUSE = WH_SURVEILLANCE
    DEFAULT_NAMESPACE = CRYPTO_SURVEILLANCE.ANALYTICS
    TYPE = LEGACY_SERVICE
    COMMENT = 'Service account for Amazon QuickSight DIRECT_QUERY to Snowflake';

GRANT ROLE SURVEILLANCE_ANALYST TO USER QUICKSIGHT_SVC;
GRANT USAGE ON WAREHOUSE WH_SURVEILLANCE TO ROLE SURVEILLANCE_ANALYST;

-- ─── QuickSight Network Policy ──────────────────────────────────────────────
-- User-level policy allowing QuickSight us-west-2 IP range.
-- Required when an account-level network policy blocks external IPs.
CREATE NETWORK POLICY IF NOT EXISTS QUICKSIGHT_NETWORK_POLICY
    ALLOWED_IP_LIST = ('54.70.204.128/27')
    COMMENT = 'Allow Amazon QuickSight us-west-2 IP range to connect';

ALTER USER QUICKSIGHT_SVC SET NETWORK_POLICY = QUICKSIGHT_NETWORK_POLICY;
