-- Suspicious-activity risk scoring and alert-volume forecast over the synthetic snapshot.
-- Predicts P(confirmed suspicious activity in the next 7 days) per account and
-- reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.SUSPICION_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, a.CATEGORY, a.KYC_TIER, a.ACCOUNT_AGE_YEARS,
       r.SELF_MATCH_PCT, r.CANCEL_RATIO_PCT,
       AVG(r.SELF_MATCH_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS SELF_MATCH_7D,
       SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS CONFIRMED_30D,
       IFF(SUM(r.CONFIRMED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'SUSPICIOUS', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.ACCOUNT_DAILY r JOIN RAW.ACCOUNTS a ON a.ID = r.ENTITY_ID
-- Market-wide volatility spikes are not account-driven, so they are excluded from training.
WHERE r.DETECTION_RULE <> 'Market volatility spike';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.SUSPICION_TRAIN AS
SELECT CATEGORY, KYC_TIER, ACCOUNT_AGE_YEARS, SELF_MATCH_PCT, CANCEL_RATIO_PCT, SELF_MATCH_7D, CONFIRMED_30D, LABEL
FROM ML.SUSPICION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.SUSPICION_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, KYC_TIER, ACCOUNT_AGE_YEARS, SELF_MATCH_PCT, CANCEL_RATIO_PCT, SELF_MATCH_7D, CONFIRMED_30D, LABEL
FROM ML.SUSPICION_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.SUSPICION_RISK_MODEL(
  INPUT_DATA => TABLE(ML.SUSPICION_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.SUSPICION_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.SUSPICION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'KYC_TIER', KYC_TIER, 'ACCOUNT_AGE_YEARS', ACCOUNT_AGE_YEARS,
           'SELF_MATCH_PCT', SELF_MATCH_PCT, 'CANCEL_RATIO_PCT', CANCEL_RATIO_PCT,
           'SELF_MATCH_7D', SELF_MATCH_7D, 'CONFIRMED_30D', CONFIRMED_30D)):probability:SUSPICIOUS::FLOAT AS P
  FROM ML.SUSPICION_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'SUSPICIOUS', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'SUSPICIOUS', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'SUSPICIOUS', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'SUSPICIOUS', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per account (label unknown, so excluded from features).
CREATE TABLE ML.SUSPICION_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.SUSPICION_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.SUSPICION_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'KYC_TIER', KYC_TIER, 'ACCOUNT_AGE_YEARS', ACCOUNT_AGE_YEARS,
           'SELF_MATCH_PCT', SELF_MATCH_PCT, 'CANCEL_RATIO_PCT', CANCEL_RATIO_PCT,
           'SELF_MATCH_7D', SELF_MATCH_7D, 'CONFIRMED_30D', CONFIRMED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:SUSPICIOUS::FLOAT, 4) AS SUSPICION_PROB_7D,
       CASE WHEN P:probability:SUSPICIOUS::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:SUSPICIOUS::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Exchange-wide alert-volume forecast (14 days) from the daily series, for investigator staffing.
CREATE VIEW ML.DAILY_ALERTS AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(ALERT_COUNT)::FLOAT AS ALERT_COUNT
FROM RAW.ACCOUNT_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.ALERT_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_ALERTS),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'ALERT_COUNT'
);

CREATE TABLE ML.ALERT_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS ALERT_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.ALERT_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
