-- =============================================================================
-- Phase 7: Case Management + Lifecycle + QuickSight Views
-- File: 07_cases.sql
-- Schema: CRYPTO_SURVEILLANCE.ANALYTICS
-- Includes: QuickSight-ready views (folded from 12_monitoring.sql)
-- =============================================================================

USE ROLE SURVEILLANCE_ADMIN;
USE DATABASE CRYPTO_SURVEILLANCE;
USE WAREHOUSE WH_SURVEILLANCE;

-- ─── CASES table ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.CASES (
    case_id             STRING        DEFAULT UUID_STRING() PRIMARY KEY,
    case_ref            STRING        COMMENT 'Human-readable reference: CASE-YYYYMMDD-NNNNN',
    entity_id           STRING        NOT NULL,
    state               STRING        DEFAULT 'OPEN'
                        COMMENT 'OPEN|IN_REVIEW|ESCALATED|SAR_FILED|CLOSED|FALSE_POSITIVE',
    priority            STRING        DEFAULT 'MEDIUM'
                        COMMENT 'CRITICAL|HIGH|MEDIUM|LOW',
    title               STRING        NOT NULL,
    summary             STRING        COMMENT 'Auto-generated by Bedrock copilot',
    sar_narrative       STRING        COMMENT 'SAR-style narrative from Bedrock',
    root_alert_ids      VARIANT       COMMENT 'ARRAY of alert_ids that triggered this case',
    alert_types         VARIANT       COMMENT 'ARRAY of distinct alert types in this case',
    peak_ml_probability FLOAT,
    composite_severity  STRING,
    assigned_to         STRING        COMMENT 'Analyst username',
    assigned_at         TIMESTAMP_LTZ,
    due_by              TIMESTAMP_LTZ COMMENT 'SLA deadline based on priority',
    sla_breached        BOOLEAN       DEFAULT FALSE,
    resolution_type     STRING        COMMENT 'TRUE_POSITIVE|FALSE_POSITIVE|INCONCLUSIVE|SAR_FILED',
    resolution_notes    STRING,
    created_at          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    closed_at           TIMESTAMP_LTZ,
    created_by          STRING        DEFAULT 'SYSTEM'
)
CLUSTER BY (state, priority, DATE_TRUNC('DAY', created_at))
DATA_RETENTION_TIME_IN_DAYS = 365
COMMENT = 'Investigation case management; one case may aggregate multiple alerts';

CREATE TABLE IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.CASE_EVENTS (
    event_id            STRING        DEFAULT UUID_STRING() PRIMARY KEY,
    case_id             STRING        NOT NULL REFERENCES CRYPTO_SURVEILLANCE.ANALYTICS.CASES(case_id),
    event_type          STRING        NOT NULL
                        COMMENT 'Type of case event',
    event_data          VARIANT       COMMENT 'Event payload (old/new state, comment text, etc.)',
    performed_by        STRING        DEFAULT 'SYSTEM',
    event_ts            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = 365
COMMENT = 'Immutable audit trail of all case state transitions and analyst actions';

-- ─── Auto-create cases from new CRITICAL/HIGH alerts ──────────────────────────
CREATE OR REPLACE PROCEDURE CRYPTO_SURVEILLANCE.ANALYTICS.SP_AUTO_CREATE_CASES()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    cases_created INT DEFAULT 0;
BEGIN
    INSERT INTO CRYPTO_SURVEILLANCE.ANALYTICS.CASES (
        case_ref, entity_id, state, priority,
        title, root_alert_ids, alert_types,
        peak_ml_probability, composite_severity,
        due_by, created_by
    )
    WITH ungrouped_alerts AS (
        SELECT
            a.entity_id,
            MAX(a.ml_fraud_probability)         AS peak_ml_prob,
            ARRAY_AGG(DISTINCT a.alert_id)      AS alert_ids,
            ARRAY_AGG(DISTINCT a.alert_type)    AS alert_types,
            MAX(a.severity)                     AS max_severity,
            COUNT(*)                            AS alert_count
        FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS a
        WHERE a.status  = 'OPEN'
          AND a.case_id IS NULL
          AND a.severity IN ('CRITICAL', 'HIGH', 'MEDIUM')
          AND a.detected_at >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
          AND NOT EXISTS (
              SELECT 1
              FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES c
              WHERE c.entity_id = a.entity_id
                AND c.state NOT IN ('CLOSED', 'FALSE_POSITIVE')
          )
        GROUP BY a.entity_id
    )
    SELECT
        'CASE-' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') || '-'
            || LPAD(ROW_NUMBER() OVER (ORDER BY max_severity DESC, alert_count DESC)::STRING, 5, '0'),
        entity_id,
        'OPEN',
        max_severity,
        alert_count::STRING || ' alert(s): ' || ARRAY_TO_STRING(alert_types, ', '),
        alert_ids,
        alert_types,
        peak_ml_prob,
        max_severity,
        DATEADD('hour',
            CASE max_severity
                WHEN 'CRITICAL' THEN 4
                WHEN 'HIGH'     THEN 24
                WHEN 'MEDIUM'   THEN 72
                ELSE 168
            END,
            CURRENT_TIMESTAMP()
        ),
        'AUTO_ALERT_TASK'
    FROM ungrouped_alerts;

    UPDATE CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS
    SET
        case_id    = c.case_id,
        status     = 'IN_REVIEW',
        updated_at = CURRENT_TIMESTAMP()
    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES c
    WHERE CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS.entity_id = c.entity_id
      AND CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS.case_id IS NULL
      AND CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS.status = 'OPEN'
      AND c.created_by = 'AUTO_ALERT_TASK'
      AND c.created_at >= DATEADD('minute', -5, CURRENT_TIMESTAMP());

    RETURN 'Cases created: ' || SQLROWCOUNT;
END;
$$;

-- ─── SLA Breach Monitor ───────────────────────────────────────────────────────
CREATE OR REPLACE PROCEDURE CRYPTO_SURVEILLANCE.ANALYTICS.SP_CHECK_SLA_BREACHES()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    UPDATE CRYPTO_SURVEILLANCE.ANALYTICS.CASES
    SET
        sla_breached = TRUE,
        updated_at   = CURRENT_TIMESTAMP()
    WHERE state NOT IN ('CLOSED', 'FALSE_POSITIVE')
      AND due_by < CURRENT_TIMESTAMP()
      AND sla_breached = FALSE;

    INSERT INTO CRYPTO_SURVEILLANCE.ANALYTICS.CASE_EVENTS
        (case_id, event_type, event_data, performed_by)
    SELECT
        case_id,
        'SLA_BREACH',
        OBJECT_CONSTRUCT(
            'due_by',    due_by::STRING,
            'breached_at', CURRENT_TIMESTAMP()::STRING,
            'priority',  priority
        ),
        'SYSTEM'
    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES
    WHERE sla_breached = TRUE
      AND updated_at   >= DATEADD('minute', -5, CURRENT_TIMESTAMP());

    RETURN 'SLA check complete';
END;
$$;

-- ─── Tasks ────────────────────────────────────────────────────────────────────
CREATE TASK IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_AUTO_CREATE_CASES
    WAREHOUSE = WH_SURVEILLANCE
    SCHEDULE  = '10 MINUTE'
    COMMENT   = 'Auto-creates investigation cases from open HIGH/CRITICAL alerts'
AS
    CALL CRYPTO_SURVEILLANCE.ANALYTICS.SP_AUTO_CREATE_CASES();

CREATE TASK IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_SLA_CHECK
    WAREHOUSE = WH_SURVEILLANCE
    SCHEDULE  = '30 MINUTE'
    COMMENT   = 'Checks and flags SLA-breached cases'
AS
    CALL CRYPTO_SURVEILLANCE.ANALYTICS.SP_CHECK_SLA_BREACHES();

-- Tasks start SUSPENDED; resume explicitly via demo_seed.sql or manually:
-- ALTER TASK CRYPTO_SURVEILLANCE.ANALYTICS.TASK_AUTO_CREATE_CASES RESUME;
-- ALTER TASK CRYPTO_SURVEILLANCE.ANALYTICS.TASK_SLA_CHECK RESUME;

-- ─── Row Access Policy (from governance) ────────────────────────────────────
USE ROLE ACCOUNTADMIN;

CREATE ROW ACCESS POLICY IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.RAP_CASES
    AS (assigned_to STRING) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('SURVEILLANCE_ADMIN', 'ACCOUNTADMIN')
    OR assigned_to IS NULL
    OR assigned_to = CURRENT_USER()
COMMENT = 'Analysts see only unassigned cases or cases assigned to them';

ALTER TABLE CRYPTO_SURVEILLANCE.ANALYTICS.CASES
    ADD ROW ACCESS POLICY CRYPTO_SURVEILLANCE.ANALYTICS.RAP_CASES ON (assigned_to);

-- Tag ALERTS and CASES for regulatory traceability
ALTER TABLE CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS
    SET TAG CRYPTO_SURVEILLANCE.HARMONISED.REGULATORY = 'AML';
ALTER TABLE CRYPTO_SURVEILLANCE.ANALYTICS.CASES
    SET TAG CRYPTO_SURVEILLANCE.HARMONISED.REGULATORY = 'SAR';

COMMENT ON DYNAMIC TABLE CRYPTO_SURVEILLANCE.HARMONISED.TRADES IS
    'Lineage: RAW.CEX_TRADES_RAW → Dynamic Table (1 min lag) → FEATURES.TRADE_FEATURES → ANALYTICS.ALERTS';
COMMENT ON TABLE CRYPTO_SURVEILLANCE.ANALYTICS.CASES IS
    'Lineage: ANALYTICS.ALERTS (auto-case) → CASES → SP_GENERATE_CASE_NARRATIVE (Bedrock) → SAR';

USE ROLE SURVEILLANCE_ADMIN;

-- ─── Reporting views for QuickSight / Streamlit ───────────────────────────────
CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_KRIs AS
SELECT
    CURRENT_DATE() AS report_date,
    (SELECT COUNT_IF(detected_at >= DATEADD('day', -1, CURRENT_TIMESTAMP()))
     FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS)                              AS alerts_24h,
    (SELECT COUNT_IF(detected_at >= DATEADD('day', -7, CURRENT_TIMESTAMP()))
     FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS)                              AS alerts_7d,
    (SELECT COUNT_IF(severity = 'CRITICAL'
                     AND detected_at >= DATEADD('day', -1, CURRENT_TIMESTAMP()))
     FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS)                              AS critical_alerts_24h,
    (SELECT COUNT_IF(state = 'OPEN')         FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS open_cases,
    (SELECT COUNT_IF(state = 'IN_REVIEW')    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS cases_in_review,
    (SELECT COUNT_IF(state = 'ESCALATED')    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS escalated_cases,
    (SELECT COUNT_IF(sla_breached = TRUE)    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS sla_breached_cases,
    (SELECT COUNT_IF(aml_risk_rating IN ('HIGH','CRITICAL'))
     FROM CRYPTO_SURVEILLANCE.HARMONISED.ENTITY)                             AS high_risk_entities,
    (SELECT COUNT_IF(sanctions_flag = TRUE)
     FROM CRYPTO_SURVEILLANCE.HARMONISED.ENTITY)                             AS sanctioned_entities;

CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_KPIs AS
SELECT
    CURRENT_DATE()                                          AS report_date,
    ROUND(AVG(CASE WHEN resolution_type = 'FALSE_POSITIVE' THEN 1.0 ELSE 0.0 END), 4)
        AS false_positive_rate,
    ROUND(AVG(DATEDIFF('minute', created_at, closed_at)), 0)
        AS avg_case_closure_minutes,
    ROUND(AVG(CASE WHEN sla_breached THEN 0.0 ELSE 1.0 END), 4)
        AS sla_compliance_rate,
    COUNT_IF(closed_at >= DATEADD('day', -7, CURRENT_TIMESTAMP())) AS cases_closed_7d,
    COUNT_IF(created_at >= DATEADD('day', -7, CURRENT_TIMESTAMP())) AS cases_opened_7d
FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES;

-- ─── QuickSight-ready views (folded from 12_monitoring.sql) ──────────────────
CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_ALERT_VOLUME AS
SELECT
    DATE_TRUNC('HOUR', detected_at)::TIMESTAMP_NTZ AS alert_hour,
    alert_type,
    severity,
    COUNT(*)                                        AS alert_count,
    COUNT(DISTINCT entity_id)                       AS unique_entities,
    AVG(ml_fraud_probability)                       AS avg_ml_score,
    COUNT_IF(status = 'OPEN')                       AS open_count,
    COUNT_IF(status = 'CLOSED')                     AS closed_count
FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS
WHERE detected_at >= DATEADD('day', -90, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3;

CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_ENTITY_HEATMAP AS
SELECT
    e.entity_id,
    e.aml_risk_rating,
    e.kyc_tier,
    e.account_type,
    e.pep_flag,
    e.sanctions_flag,
    s.ml_fraud_probability,
    s.rule_risk_tier,
    ef.cex_volume_usd_30d,
    ef.mixer_interactions_30d,
    ef.sanctioned_volume_30d,
    ef.wallet_count,
    COUNT(a.alert_id)           AS total_alerts,
    COUNT_IF(a.severity = 'CRITICAL') AS critical_alerts,
    COUNT_IF(a.severity = 'HIGH')     AS high_alerts,
    MAX(a.detected_at)          AS last_alert_ts
FROM CRYPTO_SURVEILLANCE.HARMONISED.ENTITY e
LEFT JOIN CRYPTO_SURVEILLANCE.ANALYTICS.ALERT_SCORES s    ON e.entity_id = s.entity_id
LEFT JOIN CRYPTO_SURVEILLANCE.FEATURES.ENTITY_FEATURES ef ON e.entity_id = ef.entity_id
LEFT JOIN CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS a          ON e.entity_id = a.entity_id
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12;

CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_CASE_SLA AS
SELECT
    DATE_TRUNC('DAY', created_at)::DATE     AS case_date,
    priority,
    state,
    COUNT(*)                                AS case_count,
    COUNT_IF(sla_breached = TRUE)           AS breached_count,
    ROUND(AVG(DATEDIFF('hour', created_at,
        COALESCE(closed_at, CURRENT_TIMESTAMP()))), 1) AS avg_resolution_hours,
    ROUND(AVG(peak_ml_probability), 4)      AS avg_ml_score
FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES
WHERE created_at >= DATEADD('day', -90, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3;

CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_TRADING_SUMMARY AS
SELECT
    DATE_TRUNC('DAY', trade_date)           AS trade_day,
    trading_pair,
    venue,
    COUNT(*)                                AS trade_count,
    SUM(quote_qty)                          AS volume_usd,
    AVG(price)                              AS avg_price,
    MAX(price)                              AS high_price,
    MIN(price)                              AS low_price,
    COUNT(DISTINCT account_id)              AS unique_traders
FROM CRYPTO_SURVEILLANCE.HARMONISED.TRADES
WHERE trade_ts >= DATEADD('day', -90, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3;

CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_ONCHAIN_FLOWS AS
SELECT
    DATE_TRUNC('DAY', block_ts)::DATE       AS flow_date,
    chain,
    token_symbol,
    event_type,
    COUNT(*)                                AS tx_count,
    SUM(value_decimal)                      AS total_value,
    COUNT(DISTINCT from_address)            AS unique_senders,
    COUNT(DISTINCT to_address)              AS unique_receivers,
    COUNT_IF(is_sanctioned_counterparty)    AS sanctioned_tx_count
FROM CRYPTO_SURVEILLANCE.HARMONISED.ONCHAIN_TRANSFERS
WHERE block_ts >= DATEADD('day', -90, CURRENT_TIMESTAMP())
GROUP BY 1, 2, 3, 4;

-- ─── Grants ───────────────────────────────────────────────────────────────────
GRANT SELECT ON TABLE CRYPTO_SURVEILLANCE.ANALYTICS.CASES              TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON TABLE CRYPTO_SURVEILLANCE.ANALYTICS.CASE_EVENTS        TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_KRIs             TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_KPIs             TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_ALERT_VOLUME     TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_ENTITY_HEATMAP   TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_CASE_SLA         TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_TRADING_SUMMARY  TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_QUICKSIGHT_ONCHAIN_FLOWS    TO ROLE SURVEILLANCE_ANALYST;
