-- =============================================================================
-- Phase 9: Cortex Analyst Semantic View
-- File: 09_semantic_view.sql
-- Schema: CRYPTO_SURVEILLANCE.ANALYTICS
-- Purpose: Semantic view for natural-language queries via Cortex Analyst
-- =============================================================================

USE ROLE SURVEILLANCE_ADMIN;
USE DATABASE CRYPTO_SURVEILLANCE;
USE WAREHOUSE WH_SURVEILLANCE;

CREATE OR REPLACE SEMANTIC VIEW CRYPTO_SURVEILLANCE.ANALYTICS.SURVEILLANCE_SEMANTIC_VIEW
  COMMENT = 'Semantic view for Cortex Analyst — Digital Asset Market Surveillance'
AS SEMANTIC MODEL
  NAME = 'Digital Asset Market Surveillance'
  DESCRIPTION = 'Analytics model for crypto exchange surveillance covering alerts, cases, trades, entities, and on-chain activity.'

  ENTITIES

    ENTITY alerts
      TABLE = CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS
      PRIMARY_KEY = (alert_id)
      DESCRIPTION = 'Detection alerts generated by rule-based and ML scoring across 6 typologies.'
      COLUMNS (
        alert_id DESCRIPTION = 'Unique alert identifier (UUID).',
        entity_id DESCRIPTION = 'Entity (customer/account) that triggered the alert.',
        alert_type DESCRIPTION = 'Detection typology: PUMP_AND_DUMP, WASH_TRADE, CROSS_EXCHANGE_ARBITRAGE, SANCTIONED_COUNTERPARTY, STRUCTURING, MIXER_EXPOSURE.',
        severity DESCRIPTION = 'Alert severity: CRITICAL, HIGH, MEDIUM, LOW.',
        reason DESCRIPTION = 'Human-readable explanation of why the alert fired.',
        ml_fraud_probability DESCRIPTION = 'ML fraud probability score from XGBoost model (0-1).',
        status DESCRIPTION = 'Alert lifecycle status: OPEN, IN_REVIEW, ESCALATED, CLOSED.',
        case_id DESCRIPTION = 'Case ID this alert is linked to (NULL if unassigned).',
        detected_at DESCRIPTION = 'Timestamp when the alert was generated.'
      )

    ENTITY cases
      TABLE = CRYPTO_SURVEILLANCE.ANALYTICS.CASES
      PRIMARY_KEY = (case_id)
      DESCRIPTION = 'Investigation cases aggregating one or more alerts for an entity.'
      COLUMNS (
        case_id DESCRIPTION = 'Unique case identifier (UUID).',
        case_ref DESCRIPTION = 'Human-readable case reference: CASE-YYYYMMDD-NNNNN.',
        entity_id DESCRIPTION = 'Entity under investigation.',
        state DESCRIPTION = 'Case state: OPEN, IN_REVIEW, ESCALATED, SAR_FILED, CLOSED, FALSE_POSITIVE.',
        priority DESCRIPTION = 'Case priority: CRITICAL, HIGH, MEDIUM, LOW.',
        title DESCRIPTION = 'Case title summarizing alert types.',
        peak_ml_probability DESCRIPTION = 'Highest ML score among linked alerts.',
        composite_severity DESCRIPTION = 'Overall severity derived from alert mix.',
        sla_breached DESCRIPTION = 'TRUE if the case exceeded its SLA deadline.',
        assigned_to DESCRIPTION = 'Analyst assigned to the case.',
        created_at DESCRIPTION = 'Case creation timestamp.',
        closed_at DESCRIPTION = 'Case closure timestamp (NULL if open).'
      )

    ENTITY entities
      TABLE = CRYPTO_SURVEILLANCE.HARMONISED.ENTITY
      PRIMARY_KEY = (entity_id)
      DESCRIPTION = 'Customer/entity KYC and risk profile.'
      COLUMNS (
        entity_id DESCRIPTION = 'Unique entity identifier.',
        full_name DESCRIPTION = 'Entity full name (masked for non-admin roles).',
        aml_risk_rating DESCRIPTION = 'AML risk rating: LOW, MEDIUM, HIGH, CRITICAL.',
        kyc_tier DESCRIPTION = 'KYC verification tier: BASIC, ENHANCED, FULL.',
        pep_flag DESCRIPTION = 'TRUE if Politically Exposed Person.',
        sanctions_flag DESCRIPTION = 'TRUE if on sanctions watchlist.',
        account_type DESCRIPTION = 'Account type: INDIVIDUAL, INSTITUTIONAL, MARKET_MAKER.',
        onboarded_at DESCRIPTION = 'Date the entity was onboarded.'
      )

    ENTITY trades
      TABLE = CRYPTO_SURVEILLANCE.HARMONISED.TRADES
      PRIMARY_KEY = (trade_id)
      DESCRIPTION = 'Centralised exchange (CEX) trade executions.'
      COLUMNS (
        trade_id DESCRIPTION = 'Unique trade identifier.',
        account_id DESCRIPTION = 'Account/entity that placed the trade.',
        trading_pair DESCRIPTION = 'Trading pair e.g. BTC-USDT.',
        base_asset DESCRIPTION = 'Base asset e.g. BTC.',
        side DESCRIPTION = 'Trade side: BUY or SELL.',
        price DESCRIPTION = 'Execution price in quote currency.',
        quantity DESCRIPTION = 'Quantity of base asset traded.',
        quote_qty DESCRIPTION = 'Trade value in quote currency (USD equivalent).',
        venue DESCRIPTION = 'Exchange venue name.',
        trade_ts DESCRIPTION = 'Trade execution timestamp.',
        trade_date DESCRIPTION = 'Trade date (truncated to day).'
      )

  RELATIONSHIPS
    alerts.entity_id REFERENCES entities.entity_id
      RELATIONSHIP_TYPE = many_to_one
      DESCRIPTION = 'Each alert is linked to one entity.'

    alerts.case_id REFERENCES cases.case_id
      RELATIONSHIP_TYPE = many_to_one
      DESCRIPTION = 'Each alert may be linked to one case.'

    cases.entity_id REFERENCES entities.entity_id
      RELATIONSHIP_TYPE = many_to_one
      DESCRIPTION = 'Each case investigates one entity.'

    trades.account_id REFERENCES entities.entity_id
      RELATIONSHIP_TYPE = many_to_one
      DESCRIPTION = 'Each trade is placed by one entity.'

  METRICS
    METRIC total_alerts
      EXPRESSION = COUNT(alerts.alert_id)
      DESCRIPTION = 'Total number of alerts.'

    METRIC critical_alerts
      EXPRESSION = COUNT_IF(alerts.severity = 'CRITICAL')
      DESCRIPTION = 'Number of CRITICAL severity alerts.'

    METRIC open_cases
      EXPRESSION = COUNT_IF(cases.state = 'OPEN')
      DESCRIPTION = 'Number of open investigation cases.'

    METRIC sla_breached_cases
      EXPRESSION = COUNT_IF(cases.sla_breached = TRUE)
      DESCRIPTION = 'Number of cases that breached SLA deadlines.'

    METRIC total_trade_volume
      EXPRESSION = SUM(trades.quote_qty)
      DESCRIPTION = 'Total trading volume in USD equivalent.'

    METRIC avg_ml_score
      EXPRESSION = AVG(alerts.ml_fraud_probability)
      DESCRIPTION = 'Average ML fraud probability across alerts.'

    METRIC unique_alerted_entities
      EXPRESSION = COUNT(DISTINCT alerts.entity_id)
      DESCRIPTION = 'Number of distinct entities with alerts.'

  FILTERS
    FILTER critical_only
      EXPRESSION = alerts.severity = 'CRITICAL'
      DESCRIPTION = 'Filter to only CRITICAL alerts.'

    FILTER high_risk_entities
      EXPRESSION = entities.aml_risk_rating IN ('HIGH', 'CRITICAL')
      DESCRIPTION = 'Filter to high/critical risk rated entities.'

    FILTER open_cases_only
      EXPRESSION = cases.state = 'OPEN'
      DESCRIPTION = 'Filter to open cases only.'

    FILTER last_7_days_alerts
      EXPRESSION = alerts.detected_at >= DATEADD('day', -7, CURRENT_TIMESTAMP())
      DESCRIPTION = 'Alerts from the last 7 days.'

    FILTER last_30_days_trades
      EXPRESSION = trades.trade_ts >= DATEADD('day', -30, CURRENT_TIMESTAMP())
      DESCRIPTION = 'Trades from the last 30 days.'
;

GRANT SELECT ON SEMANTIC VIEW CRYPTO_SURVEILLANCE.ANALYTICS.SURVEILLANCE_SEMANTIC_VIEW
    TO ROLE SURVEILLANCE_ANALYST;
