-- =============================================================================
-- Demo Reseed Script
-- File: sql/demo/demo_seed.sql
-- Purpose: Fast, repeatable demo reset.
--          1. Truncates RAW + derived tables (keeps schema intact)
--          2. Optionally pauses/resumes pipelines so no stale data bleeds in
--          3. Calls SP to refresh detection layer after data is loaded
--
-- Run after:
--   python scripts/generate_synthetic_data.py --scenario all --trades 50000
--
-- Or for a quick 5-min demo reset (smaller dataset):
--   python scripts/generate_synthetic_data.py --scenario all --trades 5000 --onchain 1000
--   snowsql -c <SF_CONNECTION> -f sql/demo/demo_seed.sql
--
-- Safe to run multiple times — idempotent.
-- =============================================================================

USE ROLE SURVEILLANCE_ADMIN;
USE DATABASE CRYPTO_SURVEILLANCE;
USE WAREHOUSE WH_SURVEILLANCE;

-- ─── 0. Pause pipes + tasks (IF EXISTS guards for first-run safety) ─────────
BEGIN
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_TRADES   SET PIPE_EXECUTION_PAUSED = TRUE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_ORDERS   SET PIPE_EXECUTION_PAUSED = TRUE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_BALANCES SET PIPE_EXECUTION_PAUSED = TRUE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_LOGS     SET PIPE_EXECUTION_PAUSED = TRUE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_ONCHAIN_EVENTS SET PIPE_EXECUTION_PAUSED = TRUE;
EXCEPTION
    WHEN OTHER THEN NULL;
END;

BEGIN
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_REFRESH_ALERTS       SUSPEND;
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_AUTO_CREATE_CASES     SUSPEND;
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_SLA_CHECK             SUSPEND;
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.TASK_SYNC_WALLET_DISCOVERY SUSPEND;
EXCEPTION
    WHEN OTHER THEN NULL;
END;

-- ─── 1. Truncate RAW tables ────────────────────────────────────────────────────
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.RAW.CEX_TRADES_RAW;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.RAW.CEX_ORDERS_RAW;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.RAW.CEX_BALANCES_RAW;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.RAW.CEX_LOGS_RAW;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.RAW.ONCHAIN_EVENTS_RAW;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.RAW.DLQ_ERRORS;

-- ─── 2. Truncate HARMONISED derived tables ────────────────────────────────────
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.ENTITY;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.WALLET;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.ENTITY_RELATION;

-- ─── 3. Truncate ANALYTICS operational tables ─────────────────────────────────
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.CASES;
TRUNCATE TABLE IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.CASE_EVENTS;

-- ─── 4. Log the reseed event ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.DEMO_RESEED_LOG (
    reseed_id   STRING DEFAULT UUID_STRING(),
    reseeded_at TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    reseeded_by STRING DEFAULT CURRENT_USER(),
    notes       STRING
);

INSERT INTO CRYPTO_SURVEILLANCE.ANALYTICS.DEMO_RESEED_LOG (notes)
VALUES ('Demo reseed via sql/demo/demo_seed.sql — all RAW + ANALYTICS tables truncated');

-- ─── 5. Confirm tables are empty ─────────────────────────────────────────────
SELECT 'CEX_TRADES_RAW'      AS tbl, COUNT(*) AS rows FROM CRYPTO_SURVEILLANCE.RAW.CEX_TRADES_RAW    UNION ALL
SELECT 'CEX_ORDERS_RAW',       COUNT(*) FROM CRYPTO_SURVEILLANCE.RAW.CEX_ORDERS_RAW    UNION ALL
SELECT 'CEX_BALANCES_RAW',     COUNT(*) FROM CRYPTO_SURVEILLANCE.RAW.CEX_BALANCES_RAW  UNION ALL
SELECT 'ONCHAIN_EVENTS_RAW',   COUNT(*) FROM CRYPTO_SURVEILLANCE.RAW.ONCHAIN_EVENTS_RAW UNION ALL
SELECT 'ENTITY',               COUNT(*) FROM CRYPTO_SURVEILLANCE.HARMONISED.ENTITY      UNION ALL
SELECT 'ALERTS',               COUNT(*) FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS       UNION ALL
SELECT 'CASES',                COUNT(*) FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES;

-- ─── 6. << PAUSE HERE — run the Python generator now >> ──────────────────────
--
--   python scripts/generate_synthetic_data.py \
--       --scenario all \
--       --trades   50000 \
--       --onchain  10000 \
--       --entities 200   \
--       --seed     42
--
-- Then continue with section 7 below.

-- ─── 7. Force-refresh Dynamic Tables ─────────────────────────────────────────
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.TRADES             REFRESH;
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.ORDERS             REFRESH;
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.BALANCES_SNAPSHOT  REFRESH;
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.ONCHAIN_TRANSFERS  REFRESH;
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.WALLET_DISCOVERY   REFRESH;
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.FEATURES.TRADE_FEATURES       REFRESH;
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.FEATURES.ENTITY_FEATURES      REFRESH;
ALTER DYNAMIC TABLE IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.ALERT_SCORES        REFRESH;

-- ─── 8. Run detection + case creation ────────────────────────────────────────
CALL CRYPTO_SURVEILLANCE.ANALYTICS.SP_REFRESH_ALERTS();
CALL CRYPTO_SURVEILLANCE.ANALYTICS.SP_AUTO_CREATE_CASES();

-- ─── 9. Verify demo data is ready ────────────────────────────────────────────
SELECT
    'CEX_TRADES_RAW'    AS source,  COUNT(*) AS raw_rows
FROM CRYPTO_SURVEILLANCE.RAW.CEX_TRADES_RAW
UNION ALL SELECT 'HARMONISED.TRADES',   COUNT(*) FROM CRYPTO_SURVEILLANCE.HARMONISED.TRADES
UNION ALL SELECT 'ONCHAIN_TRANSFERS',   COUNT(*) FROM CRYPTO_SURVEILLANCE.HARMONISED.ONCHAIN_TRANSFERS
UNION ALL SELECT 'ENTITY',              COUNT(*) FROM CRYPTO_SURVEILLANCE.HARMONISED.ENTITY
UNION ALL SELECT 'WALLET',              COUNT(*) FROM CRYPTO_SURVEILLANCE.HARMONISED.WALLET
UNION ALL SELECT 'TRADE_FEATURES',      COUNT(*) FROM CRYPTO_SURVEILLANCE.FEATURES.TRADE_FEATURES
UNION ALL SELECT 'ENTITY_FEATURES',     COUNT(*) FROM CRYPTO_SURVEILLANCE.FEATURES.ENTITY_FEATURES
UNION ALL SELECT 'ALERT_SCORES',        COUNT(*) FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERT_SCORES
UNION ALL SELECT 'ALERTS',              COUNT(*) FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS
UNION ALL SELECT 'CASES',               COUNT(*) FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES;

-- ─── 10. Alert breakdown (quick sanity check) ─────────────────────────────────
SELECT alert_type, severity, COUNT(*) AS cnt
FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS
GROUP BY 1, 2
ORDER BY cnt DESC;

-- ─── 11. Resume pipes + tasks for live demo ──────────────────────────────────
BEGIN
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_TRADES   SET PIPE_EXECUTION_PAUSED = FALSE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_ORDERS   SET PIPE_EXECUTION_PAUSED = FALSE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_BALANCES SET PIPE_EXECUTION_PAUSED = FALSE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_CEX_LOGS     SET PIPE_EXECUTION_PAUSED = FALSE;
    ALTER PIPE IF EXISTS CRYPTO_SURVEILLANCE.RAW.PIPE_ONCHAIN_EVENTS SET PIPE_EXECUTION_PAUSED = FALSE;
EXCEPTION
    WHEN OTHER THEN NULL;
END;

BEGIN
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_REFRESH_ALERTS       RESUME;
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_AUTO_CREATE_CASES     RESUME;
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_SLA_CHECK             RESUME;
    ALTER TASK IF EXISTS CRYPTO_SURVEILLANCE.HARMONISED.TASK_SYNC_WALLET_DISCOVERY RESUME;
EXCEPTION
    WHEN OTHER THEN NULL;
END;

-- ─── Done ─────────────────────────────────────────────────────────────────────
SELECT 'Demo reseed complete. Open Streamlit Investigator Copilot.' AS status;
