-- =============================================================================
-- Phase 6: Case Management + Lifecycle
-- File: 09_cases.sql
-- Schema: CRYPTO_SURVEILLANCE.ANALYTICS
-- Full case lifecycle from alert auto-creation through analyst review,
-- escalation, SAR referral, and closure.
-- =============================================================================

USE ROLE SURVEILLANCE_ADMIN;
USE DATABASE CRYPTO_SURVEILLANCE;
USE WAREHOUSE WH_ANALYTICS;

-- ─── CASES table ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.CASES (
    case_id             STRING        DEFAULT UUID_STRING() PRIMARY KEY,
    case_ref            STRING        COMMENT 'Human-readable reference: CASE-YYYYMMDD-NNNNN',
    entity_id           STRING        NOT NULL,
    -- Case state machine
    state               STRING        DEFAULT 'OPEN'
                        COMMENT 'OPEN|IN_REVIEW|ESCALATED|SAR_FILED|CLOSED|FALSE_POSITIVE',
    priority            STRING        DEFAULT 'MEDIUM'
                        COMMENT 'CRITICAL|HIGH|MEDIUM|LOW',
    -- Case content
    title               STRING        NOT NULL,
    summary             STRING        COMMENT 'Auto-generated by Bedrock copilot',
    sar_narrative       STRING        COMMENT 'SAR-style narrative from Bedrock',
    root_alert_ids      VARIANT       COMMENT 'ARRAY of alert_ids that triggered this case',
    alert_types         VARIANT       COMMENT 'ARRAY of distinct alert types in this case',
    -- Risk scores
    peak_ml_probability FLOAT,
    composite_severity  STRING,
    -- Assignment and SLA
    assigned_to         STRING        COMMENT 'Analyst username',
    assigned_at         TIMESTAMP_LTZ,
    due_by              TIMESTAMP_LTZ COMMENT 'SLA deadline based on priority',
    sla_breached        BOOLEAN       DEFAULT FALSE,
    -- Resolution
    resolution_type     STRING        COMMENT 'TRUE_POSITIVE|FALSE_POSITIVE|INCONCLUSIVE|SAR_FILED',
    resolution_notes    STRING,
    -- Audit
    created_at          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    closed_at           TIMESTAMP_LTZ,
    created_by          STRING        DEFAULT 'SYSTEM'
)
CLUSTER BY (state, priority, DATE_TRUNC('DAY', created_at))
DATA_RETENTION_TIME_IN_DAYS = 365
COMMENT = 'Investigation case management; one case may aggregate multiple alerts';

-- Case events / audit trail
CREATE TABLE IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.CASE_EVENTS (
    event_id            STRING        DEFAULT UUID_STRING() PRIMARY KEY,
    case_id             STRING        NOT NULL REFERENCES CRYPTO_SURVEILLANCE.ANALYTICS.CASES(case_id),
    event_type          STRING        NOT NULL  -- STATE_CHANGE|ASSIGNMENT|COMMENT|SAR_GENERATED|EVIDENCE_ADDED
                        COMMENT 'Type of case event',
    event_data          VARIANT       COMMENT 'Event payload (old/new state, comment text, etc.)',
    performed_by        STRING        DEFAULT 'SYSTEM',
    event_ts            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
)
DATA_RETENTION_TIME_IN_DAYS = 365
COMMENT = 'Immutable audit trail of all case state transitions and analyst actions';

-- ─── Auto-create cases from new CRITICAL/HIGH alerts ──────────────────────────
CREATE OR REPLACE PROCEDURE CRYPTO_SURVEILLANCE.ANALYTICS.SP_AUTO_CREATE_CASES()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    cases_created INT DEFAULT 0;
    priority_sla_hours VARIANT DEFAULT OBJECT_CONSTRUCT(
        'CRITICAL', 4, 'HIGH', 24, 'MEDIUM', 72, 'LOW', 168
    );
BEGIN
    -- For each entity with open alerts not yet in an open case, create a case.
    -- Fixed: replaced invalid HAVING c.entity_id IS NULL (non-grouped col after LEFT JOIN)
    -- with a NOT EXISTS subquery, which is unambiguous and correct.
    INSERT INTO CRYPTO_SURVEILLANCE.ANALYTICS.CASES (
        case_ref, entity_id, state, priority,
        title, root_alert_ids, alert_types,
        peak_ml_probability, composite_severity,
        due_by, created_by
    )
    WITH ungrouped_alerts AS (
        SELECT
            a.entity_id,
            MAX(a.ml_fraud_probability)         AS peak_ml_prob,
            ARRAY_AGG(DISTINCT a.alert_id)      AS alert_ids,
            ARRAY_AGG(DISTINCT a.alert_type)    AS alert_types,
            MAX(a.severity)                     AS max_severity,
            COUNT(*)                            AS alert_count
        FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS a
        WHERE a.status  = 'OPEN'
          AND a.case_id IS NULL
          AND a.severity IN ('CRITICAL', 'HIGH', 'MEDIUM')
          AND a.detected_at >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
          AND NOT EXISTS (
              SELECT 1
              FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES c
              WHERE c.entity_id = a.entity_id
                AND c.state NOT IN ('CLOSED', 'FALSE_POSITIVE')
          )
        GROUP BY a.entity_id
    )
    SELECT
        'CASE-' || TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') || '-'
            || LPAD(ROW_NUMBER() OVER (ORDER BY max_severity DESC, alert_count DESC)::STRING, 5, '0'),
        entity_id,
        'OPEN',
        max_severity,
        alert_count::STRING || ' alert(s): ' || ARRAY_TO_STRING(alert_types, ', '),
        alert_ids,
        alert_types,
        peak_ml_prob,
        max_severity,
        DATEADD('hour',
            CASE max_severity
                WHEN 'CRITICAL' THEN 4
                WHEN 'HIGH'     THEN 24
                WHEN 'MEDIUM'   THEN 72
                ELSE 168
            END,
            CURRENT_TIMESTAMP()
        ),
        'AUTO_ALERT_TASK'
    FROM ungrouped_alerts;

    -- Link alerts back to their new cases.
    -- Fixed: Snowflake does not support table alias on UPDATE target; removed alias.
    UPDATE CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS
    SET
        case_id    = c.case_id,
        status     = 'IN_REVIEW',
        updated_at = CURRENT_TIMESTAMP()
    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES c
    WHERE CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS.entity_id = c.entity_id
      AND CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS.case_id IS NULL
      AND CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS.status = 'OPEN'
      AND c.created_by = 'AUTO_ALERT_TASK'
      AND c.created_at >= DATEADD('minute', -5, CURRENT_TIMESTAMP());

    RETURN 'Cases created: ' || SQLROWCOUNT;
END;
$$;

-- ─── SLA Breach Monitor ───────────────────────────────────────────────────────
CREATE OR REPLACE PROCEDURE CRYPTO_SURVEILLANCE.ANALYTICS.SP_CHECK_SLA_BREACHES()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    UPDATE CRYPTO_SURVEILLANCE.ANALYTICS.CASES
    SET
        sla_breached = TRUE,
        updated_at   = CURRENT_TIMESTAMP()
    WHERE state NOT IN ('CLOSED', 'FALSE_POSITIVE')
      AND due_by < CURRENT_TIMESTAMP()
      AND sla_breached = FALSE;

    -- Log breach events
    INSERT INTO CRYPTO_SURVEILLANCE.ANALYTICS.CASE_EVENTS
        (case_id, event_type, event_data, performed_by)
    SELECT
        case_id,
        'SLA_BREACH',
        OBJECT_CONSTRUCT(
            'due_by',    due_by::STRING,
            'breached_at', CURRENT_TIMESTAMP()::STRING,
            'priority',  priority
        ),
        'SYSTEM'
    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES
    WHERE sla_breached = TRUE
      AND updated_at   >= DATEADD('minute', -5, CURRENT_TIMESTAMP());

    RETURN 'SLA check complete';
END;
$$;

-- ─── Tasks ────────────────────────────────────────────────────────────────────
CREATE TASK IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_AUTO_CREATE_CASES
    WAREHOUSE = WH_ANALYTICS
    SCHEDULE  = '10 MINUTE'
    COMMENT   = 'Auto-creates investigation cases from open HIGH/CRITICAL alerts'
AS
    CALL CRYPTO_SURVEILLANCE.ANALYTICS.SP_AUTO_CREATE_CASES();

CREATE TASK IF NOT EXISTS CRYPTO_SURVEILLANCE.ANALYTICS.TASK_SLA_CHECK
    WAREHOUSE = WH_ANALYTICS
    SCHEDULE  = '30 MINUTE'
    COMMENT   = 'Checks and flags SLA-breached cases'
AS
    CALL CRYPTO_SURVEILLANCE.ANALYTICS.SP_CHECK_SLA_BREACHES();

-- Tasks start SUSPENDED; resume explicitly via demo_seed.sql or manually:
-- ALTER TASK CRYPTO_SURVEILLANCE.ANALYTICS.TASK_AUTO_CREATE_CASES RESUME;
-- ALTER TASK CRYPTO_SURVEILLANCE.ANALYTICS.TASK_SLA_CHECK RESUME;

-- ─── Reporting views for QuickSight / Streamlit ───────────────────────────────
-- Fixed: removed FULL JOIN ... ON TRUE (cross-join that multiplied rows by millions).
-- Each metric is now an independent scalar subquery — zero risk of row-multiplication.
CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_KRIs AS
SELECT
    CURRENT_DATE() AS report_date,
    -- Alert volume (independent subqueries, no cross-join)
    (SELECT COUNT_IF(detected_at >= DATEADD('day', -1, CURRENT_TIMESTAMP()))
     FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS)                              AS alerts_24h,
    (SELECT COUNT_IF(detected_at >= DATEADD('day', -7, CURRENT_TIMESTAMP()))
     FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS)                              AS alerts_7d,
    (SELECT COUNT_IF(severity = 'CRITICAL'
                     AND detected_at >= DATEADD('day', -1, CURRENT_TIMESTAMP()))
     FROM CRYPTO_SURVEILLANCE.ANALYTICS.ALERTS)                              AS critical_alerts_24h,
    -- Case metrics
    (SELECT COUNT_IF(state = 'OPEN')         FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS open_cases,
    (SELECT COUNT_IF(state = 'IN_REVIEW')    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS cases_in_review,
    (SELECT COUNT_IF(state = 'ESCALATED')    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS escalated_cases,
    (SELECT COUNT_IF(sla_breached = TRUE)    FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES) AS sla_breached_cases,
    -- Risk coverage
    (SELECT COUNT_IF(aml_risk_rating IN ('HIGH','CRITICAL'))
     FROM CRYPTO_SURVEILLANCE.HARMONISED.ENTITY)                             AS high_risk_entities,
    (SELECT COUNT_IF(sanctions_flag = TRUE)
     FROM CRYPTO_SURVEILLANCE.HARMONISED.ENTITY)                             AS sanctioned_entities;

CREATE OR REPLACE VIEW CRYPTO_SURVEILLANCE.ANALYTICS.VW_KPIs AS
SELECT
    CURRENT_DATE()                                          AS report_date,
    -- Detection quality
    ROUND(AVG(CASE WHEN resolution_type = 'FALSE_POSITIVE' THEN 1.0 ELSE 0.0 END), 4)
        AS false_positive_rate,
    ROUND(AVG(DATEDIFF('minute', created_at, closed_at)), 0)
        AS avg_case_closure_minutes,
    ROUND(AVG(CASE WHEN sla_breached THEN 0.0 ELSE 1.0 END), 4)
        AS sla_compliance_rate,
    -- Throughput
    COUNT_IF(closed_at >= DATEADD('day', -7, CURRENT_TIMESTAMP())) AS cases_closed_7d,
    COUNT_IF(created_at >= DATEADD('day', -7, CURRENT_TIMESTAMP())) AS cases_opened_7d
FROM CRYPTO_SURVEILLANCE.ANALYTICS.CASES;

-- Grants
GRANT SELECT ON TABLE CRYPTO_SURVEILLANCE.ANALYTICS.CASES              TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON TABLE CRYPTO_SURVEILLANCE.ANALYTICS.CASE_EVENTS        TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_KRIs             TO ROLE SURVEILLANCE_ANALYST;
GRANT SELECT ON VIEW  CRYPTO_SURVEILLANCE.ANALYTICS.VW_KPIs             TO ROLE SURVEILLANCE_ANALYST;
